import type { Metadata } from 'next';

export const metadata: Metadata = { title: 'Terms & Conditions', description: 'ToolKH Terms and Conditions' };

export default function TermsPage() {
  return (
    <div style={{ maxWidth: 800, margin: '0 auto', padding: '1.5rem 1rem' }}>
      <h1 style={{ fontSize: '1.75rem', fontWeight: 800, color: 'var(--text)', marginBottom: '1.5rem' }}>Terms & Conditions</h1>
      <div className="card" style={{ padding: '1.5rem' }}>
        <div className="prose-content">
          <p><em>Last updated: December 2024</em></p>
          <h2>Acceptance of Terms</h2>
          <p>By using ToolKH, you agree to these terms. If you do not agree, please do not use the site.</p>
          <h2>Use of Tools</h2>
          <p>Our tools are provided free of charge for personal and commercial use. You may not use our tools for illegal activities or to harm others.</p>
          <h2>No Warranty</h2>
          <p>Tools are provided &quot;as is&quot; without warranty. We do not guarantee accuracy of results. Always verify important calculations independently.</p>
          <h2>Limitation of Liability</h2>
          <p>ToolKH is not liable for any damages arising from the use of our tools. Use at your own risk.</p>
          <h2>Intellectual Property</h2>
          <p>The ToolKH name, logo, and website design are our intellectual property. Tool outputs generated by users belong to those users.</p>
          <h2>Changes to Terms</h2>
          <p>We may update these terms at any time. Continued use of the site constitutes acceptance of updated terms.</p>
        </div>
      </div>
    </div>
  );
}
